<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<template x-if="segment.code === 'discount'">
    <div :class="wrapperClass">
        <div x-text="segment.title"></div>
        <div x-text="hyva.formatPrice(segment.value)" class="justify-self-end"></div>
    </div>
</template>
