<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<!-- display subtotal excluding tax -->
<template x-if="segment.code === 'grand_total' && checkoutConfig.includeTaxInGrandTotal">
    <div class="mt-6 mb-12 divide-y">
        <div :class="wrapperClassTotals">
            <span x-text="`${segment.title} ${includingTaxMessage}`" class="font-semibold"></span>
            <span x-text="hyva.formatPrice(segment.value)" class="justify-self-end"></span>
        </div>
        <div :class="wrapperClass" class="text-base">
            <span x-text="`${segment.title} ${excludingTaxMessage}`" class="font-semibold"></span>
            <span x-text="hyva.formatPrice(totalsData.grand_total)" class="justify-self-end"></span>
        </div>
    </div>
</template>

<!-- display subtotal including tax -->
<template x-if="segment.code === 'grand_total' && !checkoutConfig.includeTaxInGrandTotal">
    <div :class="wrapperClassTotals" class="mt-6 mb-12">
        <span x-text="`${segment.title}`" class="font-semibold"></span>
        <span x-text="hyva.formatPrice(segment.value)" class="justify-self-end"></span>
    </div>
</template>
