<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<!-- display subtotal excluding tax -->
<template x-if="segment.code === 'grand_total' && checkoutConfig.includeTaxInGrandTotal">
    <div class="contents">
        <div :class="wrapperClassTotals">
            <dt x-html="`${segment.title} ${includingTaxMessage}`"></dt>
            <dd x-text="hyva.formatPrice(segment.value)"></dd>
        </div>
        <div :class="wrapperClass">
            <dt x-html="`${segment.title} ${excludingTaxMessage}`"></dt>
            <dd x-text="hyva.formatPrice(totalsData.grand_total)"></dd>
        </div>
    </div>
</template>

<!-- display subtotal including tax -->
<template x-if="segment.code === 'grand_total' && !checkoutConfig.includeTaxInGrandTotal">
    <div :class="wrapperClassTotals">
        <dt x-html="`${segment.title}`"></dt>
        <dd x-text="hyva.formatPrice(segment.value)"></dd>
    </div>
</template>
