<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<!-- display shipping including and excluding tax -->
<template x-if="segment.code === 'shipping' && quoteData.is_virtual === 0 && !!shippingMethod && 'both' === checkoutConfig.reviewShippingDisplayMode">
    <div :class="wrapperClass">
        <dt x-text="`${segment.title} ${excludingTaxMessage}`"></dt>
        <dd x-text="hyva.formatPrice(totalsData.shipping_amount)" class="justify-self-end"></dd>
        <dt x-text="`${segment.title} ${includingTaxMessage}`"></dt>
        <dd x-text="hyva.formatPrice(totalsData.shipping_incl_tax)" class="justify-self-end"></dd>
    </div>
</template>

<!-- display shipping excluding tax -->
<template x-if="segment.code === 'shipping' && quoteData.is_virtual === 0 && !!shippingMethod && 'excluding' === checkoutConfig.reviewShippingDisplayMode">
    <div :class="wrapperClass">
        <dt x-text="segment.title"></dt>
        <dd x-text="hyva.formatPrice(segment.value)" class="justify-self-end"></dd>
    </div>
</template>

<!-- display shipping including tax -->
<template x-if="segment.code === 'shipping' && quoteData.is_virtual === 0 && !!shippingMethod && 'including' === checkoutConfig.reviewShippingDisplayMode">
    <div :class="wrapperClass">
        <dt x-text="segment.title"></dt>
        <dd x-text="hyva.formatPrice(totalsData.shipping_incl_tax)" class="justify-self-end"></dd>
    </div>
</template>
