<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<!-- display subtotal including and excluding tax -->
<template x-if="segment.code === 'subtotal' && 'both' === checkoutConfig.reviewTotalsDisplayMode">
    <div :class="wrapperClass">
        <span x-html="`${segment.title} (${excludingTaxMessage})`"></span>
        <span x-text="hyva.formatPrice(totalsData.subtotal)" class="justify-self-end"></span>
        <span x-html="`${segment.title} (${includingTaxMessage})`"></span>
        <span x-text="hyva.formatPrice(totalsData.subtotal_incl_tax)" class="justify-self-end"></span>
    </div>
</template>

<!-- display subtotal excluding tax -->
<template x-if="segment.code === 'subtotal' && 'excluding' === checkoutConfig.reviewTotalsDisplayMode">
    <div :class="wrapperClass">
        <span x-html="segment.title"></span>
        <span x-text="hyva.formatPrice(totalsData.subtotal)" class="justify-self-end"></span>
    </div>
</template>

<!-- display subtotal including tax -->
<template x-if="segment.code === 'subtotal' && 'including' === checkoutConfig.reviewTotalsDisplayMode">
    <div :class="wrapperClass">
        <span x-html="segment.title"></span>
        <span x-text="hyva.formatPrice(totalsData.subtotal_incl_tax)" class="justify-self-end"></span>
    </div>
</template>
