<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<template x-if="segment.code === 'tax' && (segment.value > 0 || checkoutConfig.isZeroTaxDisplayed)">
    <div>
        <template x-if="!(segment.value > 0 && checkoutConfig.isFullTaxSummaryDisplayed)">
            <div :class="wrapperClass">
                <dt x-text="segment.title"></dt>
                <dd x-text="hyva.formatPrice(segment.value)" class="justify-self-end"></dd>
            </div>
        </template>

        <template x-if="segment.value > 0 && checkoutConfig.isFullTaxSummaryDisplayed">
            <details class="group">
                <summary class="block cursor-pointer [&::-webkit-details-marker]:hidden">
                    <span :class="wrapperClass">
                        <dt x-text="segment.title"></dt>
                        <dd class="inline-flex items-center gap-x-1 justify-self-end">
                            <span x-text="hyva.formatPrice(segment.value)"></span>
                            <?= $heroicons->chevronDownHtml('transform group-open:rotate-180', 18, 18, ['aria-hidden' => 'true']); ?>
                        </dd>
                    </span>
                </summary>
                <div>
                    <template x-for="(taxItem, index) in segment.extension_attributes.tax_grandtotal_details" :key="index">
                        <dl :class="wrapperClass">
                            <dt>
                                <template x-for="(taxRate, index) in taxItem.rates">
                                    <div x-text="`${taxRate.title} (${taxRate.percent}%)`"></div>
                                </template>
                            </dt>
                            <dd x-text="hyva.formatPrice(taxItem.amount)" class="justify-self-end"></dd>
                        </dl>
                    </template>
                </div>
            </div>
        </template>
    </div>
</template>
