<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class);
$menuItems = $viewModelNavigation->getNavigation(4);

?>
<div class="z-20 order-2 sm:order-1 lg:order-2 navigation"
     x-on:resize.window.debounce.200="menu.checkIsSmallResolution()"
>
    <!-- mobile -->
    <div class="bg-container-lighter lg:hidden"
         :class="{'min-h-screen fixed top-0 left-0 w-full' : menu.open}"
         @toggle-mobile-menu.window="menu.open = !menu.open"
         @keydown.window.escape="menu.open=false"
    >
        <div class="flex items-baseline justify-between menu-icon">
            <div class="flex justify-end w-full">
                <a @click="$dispatch('toggle-mobile-menu')"
                       class="flex items-center justify-center cursor-pointer"
                       :class="{ 'ml-auto': menu.open }">
                    <svg class="w-16 h-16 p-4 fill-current hidden"
                         :class="{ 'hidden' : !menu.open, 'block': menu.open }"
                         xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                         viewBox="0 0 20 20">
                        <path
                              fill-rule="evenodd" clip-rule="evenodd"
                              d="M18.278 16.864a1 1 0 0 1-1.414 1.414l-4.829-4.828-4.828 4.828a1 1 0 0
                          1-1.414-1.414l4.828-4.829-4.828-4.828a1 1 0 0 1 1.414-1.414l4.829 4.828
                          4.828-4.828a1 1 0 1 1 1.414 1.414l-4.828 4.829 4.828 4.828z">
                        </path>
                    </svg>
                    <svg class="w-12 h-12 p-3 fill-current block"
                         :class="{ 'hidden' : menu.open, 'block': !menu.open }"
                         xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                         viewBox="0 0 20 20">
                        <path
                              d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z">
                        </path>
                    </svg>
                </a>
            </div>
        </div>

        <nav
            class="hidden w-full duration-150 ease-in-out transform transition-display border-t border-container"
            :class="{ 'hidden' : !menu.open }"
        >
        <?php foreach ($menuItems as $index => $menuItem): ?>
            <div>
                <span
                    class="flex items-center transition-transform duration-150 ease-in-out transform"
                    :class="{
                        '-translate-x-full' : menu.mobilePanelActiveId,
                        'translate-x-0' : !menu.mobilePanelActiveId
                    }"
                >
                    <a class="w-full flex items-center px-8 py-4 cursor-pointer bg-container-lighter border-container border-b hover:bg-container-darker hover:underline
                    <?php if ($menuItem['is_active'] || $menuItem['has_active']): ?>
                            underline
                    <?php endif; ?>"
                       href="<?= (string) $menuItem['url'] ?>"
                       title="<?= (string) $menuItem['name'] ?>">
                        <?= (string) $menuItem['name'] ?>
                    </a>
                    <?php if (!empty($menuItem['childData'])): ?>
                    <a class="absolute bg-container-lighter border border-container flex h-8 mr-8 right-0 rounded w-8 hover:bg-container hover:border-container cursor-pointer"
                          @click="menu.mobilePanelActiveId =
                          menu.mobilePanelActiveId === '<?= (string) $index ?>' ?
                           0 : '<?= (string) $index ?>'"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" height="24" width="24"
                             stroke="currentColor"
                             class="w-full h-full p-1"
                        >
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
                        </svg>
                    </a>
                    <?php endif; ?>
                </span>
                <?php if (!empty($menuItem['childData'])): ?>
                    <div
                        class="absolute top-0 right-0 z-10 w-full h-full transition-transform duration-200 ease-in-out
                            translate-x-full transform bg-container-lighter"
                        :class="{
                            'translate-x-full' : menu.mobilePanelActiveId !== '<?= (string) $index ?>',
                            'translate-x-0' : menu.mobilePanelActiveId === '<?= (string) $index ?>',
                        }"
                    >
                        <a class="flex items-center px-8 py-4 cursor-pointer bg-container border-container border-b"
                              @click="menu.mobilePanelActiveId = 0"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" height="24"
                                 width="24"
                                 stroke="currentColor">
                              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M15 19l-7-7 7-7"/>
                            </svg>
                            <span class="ml-4">
                                <?= (string) $menuItem['name'] ?>
                            </span>
                        </a>
                        <a href="<?= (string) $menuItem['url'] ?>" title="<?= (string) $menuItem['name'] ?>"
                           class="w-full flex items-center px-8 py-4 cursor-pointer bg-container-lighter border-container border-b hover:bg-container-darker hover:underline
                           <?php if ($menuItem['is_active']): ?>
                                  underline
                           <?php endif; ?>">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                 viewBox="0 0 24 24" height="24"
                                 width="24"></svg>
                            <span class="ml-4"><?= $escaper->escapeHtml(__('View All')) ?></span></a>
                        <?php foreach ($menuItem['childData'] as $subMenuItem): ?>

                            <a href="<?= (string) $subMenuItem['url'] ?>"
                               title="<?= (string) $subMenuItem['name'] ?>"
                               class="w-full flex items-center px-8 py-4 cursor-pointer bg-container-lighter border-container border-b hover:bg-container-darker hover:underline
                               <?php if ($subMenuItem['is_active'] || $subMenuItem['has_active']): ?>
                                      underline
                               <?php endif; ?>"
                            >
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                     viewBox="0 0 24 24" height="24"
                                     width="24"></svg>
                                <span class="ml-4 text-base text-gray-700 lg:ml-0">
                                    <?= (string) $subMenuItem['name'] ?>
                                </span>
                            </a>

                        <?php endforeach; ?>
                    </div>

                <?php endif; ?>
            </div>
        <?php endforeach; ?>
        </nav>
    </div>

    <!-- desktop -->
    <div class="hidden lg:block lg:relative lg:min-h-0 lg:px-8 lg:w-auto lg:pt-0">
        <nav
            class="w-full duration-150 ease-in-out transform flex justify-start
            w-auto relative min-h-0 -left-6 transition-display"
        >
            <?php foreach ($menuItems as $index => $menuItem): ?>
                <div class="relative mr-2"
                     @mouseenter="menu.hoverPanelActiveId = '<?= (string) $index ?>'"
                     @mouseleave="menu.hoverPanelActiveId = 0"
                >
                    <span class="flex items-center p-3 text-md block bg-opacity-95">
                        <a class="py-3 text-base text-gray-700 w-full hover:underline
                        <?php if ($menuItem['is_active'] || $menuItem['has_active']): ?>
                            underline
                        <?php endif; ?>"
                           href="<?= (string) $menuItem['name'] ?>"
                           title="<?= (string) $menuItem['name'] ?>"
                        >
                            <?= (string) $menuItem['name'] ?>
                        </a>
                </span>
                    <?php if (!empty($menuItem['childData'])): ?>
                        <div
                            class="hidden absolute z-10 shadow-lg -ml-6 px-6 py-4 bg-container-lighter bg-opacity-95"
                            :class="{
                            'hidden' : menu.hoverPanelActiveId !== '<?= (string) $index ?>',
                            'block' : menu.hoverPanelActiveId === '<?= (string) $index ?>'
}"
                        >
                            <?php foreach ($menuItem['childData'] as $subMenuItem): ?>
                                <a href="<?= (string) $subMenuItem['url'] ?>"
                                   title="<?= (string) $subMenuItem['name'] ?>"
                                   class="w-full py-1 my-1 block px-3 first:mt-0 hover:underline whitespace-no-wrap
                                    <?php if ($subMenuItem['is_active'] || $subMenuItem['has_active']): ?>
                                      underline
                                    <?php endif; ?>"
                                >
                                    <span class="text-base text-gray-700">
                                        <?= (string) $subMenuItem['name'] ?>
                                    </span>
                                </a>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </nav>
    </div>

</div>
<script>
    function initHeaderNavigation($this) {
        var checkIsSmallResolution = function () {
            var menuIcon = document.querySelector('.menu-icon');
            return !(
                window.getComputedStyle(menuIcon).display === 'none' ||
                window.getComputedStyle(menuIcon).visibility === 'hidden'
            );
        };
        return {
            navigation: Object.values(<?= /** @noEscape */ \json_encode($menuItems) ?>),
            isSmallResolution: checkIsSmallResolution(),
            checkIsSmallResolution: function () {
                this.isSmallResolution = checkIsSmallResolution();
            },
            mobilePanelActiveId: null,
            hoverPanelActiveId: null,
            open: false
        }
    }
</script>

