<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Customer\Block\Widget\Telephone;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Telephone $block */
?>

<div class="field telephone <?= $block->isRequired() ? 'required' : '' ?>">
    <label for="telephone" class="label">
        <span>
            <?= $escaper->escapeHtml(__('Phone Number')) ?>
        </span>
    </label>
    <div class="control">
        <input type="number"
               name="telephone"
               id="telephone"
               required
               min="3"
               @change="changeTelephone($event.target)"
               value="<?= $escaper->escapeHtmlAttr($block->getTelephone()) ?>"
               title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
               class="form-input <?= $escaper->escapeHtmlAttr(
                   $block->getAttributeValidationClass('telephone')
               ) ?>"
        >
    </div>
</div>
