<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var StoreConfig $storeConfig */

$storeConfig = $viewModels->require(StoreConfig::class);
$siteKeyV2 = $storeConfig->getStoreConfig('recaptcha_frontend/type_invisible/public_key');
$uniqueId = '_' . uniqid();
?>

<script src="https://www.google.com/recaptcha/api.js" async defer></script>

<div class="g-recaptcha"
     data-sitekey="<?= $siteKeyV2 ?>"
     data-callback="onSubmit<?= $uniqueId ?>"
     data-size="invisible"
     id="recaptcha<?= $uniqueId ?>"
>
</div>

<script>
    (function () {
        'use strict';
        const captchaElement = document.getElementById('recaptcha<?= $uniqueId ?>');
        const formElement = captchaElement.closest('form');

        if (formElement) {
            const submitHandler = function(e) {
                console.log(e);
                e.preventDefault();
                grecaptcha.execute();
                debugger;
            };

            window.onSubmit<?= $uniqueId ?> = function () {
                // formElement.removeEventHandler('submit', submitHandler);
                alert('hello')
                formElement.dispatchEvent(new Event('submit'));

            };

            formElement.addEventListener('submit', submitHandler);
        }
    })();
</script>
