<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;

/** @var $escaper Escaper */

$product = $block->getProduct();
?>
<?php if ($product->isSaleable() && $block->hasOptions()): ?>
<div id="bundleSummary"
     class="block-bundle-summary card w-full sm:w-1/2 md:w-1/3">
    <div class="title mb-2">
        <h3 class="text-gray-900 text-2xl title-font font-base text-center md:text-left w-full">
            <?= $block->escapeHtml(__('Your Customization')) ?>
        </h3>
    </div>
    <div class="content">
        <div class="bundle-info">
            <div class="product-details">
                <h3 class="product-name text-lg font-semibold">
                    <?= $block->escapeHtml($product->getName()) ?>
                </h3>

                <?= $block->getBlockHtml('product.info.form') ?>

                <?= $block->getChildHtml("product.info.bundle.price") ?>

                <?php if ($product->isSaleable()): ?>
                <div class="flex my-4 sm:mt-0">
                    <?= $block->getChildHtml("product.info.quantity") ?>
                    <?= $block->getChildHtml("product.info.addtocart") ?>
                </div>
                <?php endif; ?>

                </div>

            </div>
            <div class="tier-price-container my-2 py-4">
                <?= $block->getChildHtml("product.price.tier") ?>
            </div>

        </div>
        <div class="bundle-summary">
            <strong class="subtitle"><?= $block->escapeHtml(__('Summary')) ?></strong>
            <div id="bundle-summary" data-container="product-summary">
                <ul data-mage-init='{"productSummary": []}' class="bundle items"></ul>
                <script data-template="bundle-summary" type="text/x-magento-template">
                    <li>
                        <strong class="label"><%- data._label_ %>:</strong>
                        <div data-container="options"></div>
                    </li>
                </script>
                <script data-template="bundle-option" type="text/x-magento-template">
                    <div><?= /* @noEscape */ __('%1 x %2', '<%- data._quantity_ %>', '<%- data._label_ %>') ?></div>
                </script>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
