<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */
?>

<script>
    (() => {
        const pageTypeStorageKey = 'view-transition-to-gallery-page-type';
        const transitionName = 'view-transition-to-gallery';

        const setTransitionName = async (url, promise) => {
            if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

            const productGallery = document.getElementById('gallery-main');
            const productListItem = Array.from(document.querySelectorAll('.product-item-photo'))
                .find((anchor) => anchor.href === url);
            const targetElement = productListItem || productGallery;

            if (targetElement) {
                targetElement.style.viewTransitionName = transitionName;

                try {
                    await promise;
                } finally {
                    targetElement.style.viewTransitionName = '';
                }
            }
        };

        const getPageType = () => {
            return document.body.classList.contains('catalog-product-view') ? 'product-page' : 'other';
        };

        window.addEventListener('pageswap', (e) => {
            if (!e.viewTransition) return;
            const pageType = getPageType();
            const target = new URL(e.activation.entry.url);

            sessionStorage.setItem(pageTypeStorageKey, pageType);
            setTransitionName(target.href, e.viewTransition.finished);
        });

        window.addEventListener('pagereveal', (e) => {
            if (!e.viewTransition || (window.navigation && !window.navigation.activation.from)) return;
            const previousPageType = sessionStorage.getItem(pageTypeStorageKey);
            const pageType = getPageType();
            sessionStorage.removeItem(pageTypeStorageKey);

            if (previousPageType === pageType) return;
            const target = new URL(window.navigation.activation.from.url);
            setTransitionName(target.href, e.viewTransition.finished);
        });
    })();
</script>
<?php $hyvaCsp->registerInlineScript() ?>
