<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Checkout\Block\Onepage\Failure;

/** @var Escaper $escaper */
/** @var Failure $block */
?>
<?php if ($block->getRealOrderId()): ?>
    <p><?= $escaper->escapeHtml(__('Order #') . $block->getRealOrderId()) ?></p>
<?php endif ?>
<?php if ($error = $block->getErrorMessage()): ?>
    <p><?= $escaper->escapeHtml($error) ?></p>
<?php endif ?>
<p><?= $escaper->escapeHtml(
    __('Click <a href="%1">here</a> to continue shopping.', $escaper->escapeUrl($block->getContinueShoppingUrl())),
    ['a']
) ?>
</p>
