<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Actions;

/** @var Actions $block */
?>
<?php $children = $block->getChildNames(); ?>
<?php if ($children) : ?>
    <div class="<?= $block->escapeHtmlAttr($block->getCssClass()) ?> mt-2">
        <?php foreach ($children as $childName) : ?>
            <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
        <?php endforeach;?>
    </div>
<?php endif; ?>
