<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Comment;
use Magento\Wishlist\Model\Item;

/* @var Comment $block  */

/* @var Item $item */
$item = $block->getItem();
?>
<div class="field comment-box">
    <label class="label" for="product-item-comment-<?= $block->escapeHtmlAttr($item->getWishlistItemId()) ?>">
        <span><?= $block->escapeHtml(__('Comment')) ?></span>
    </label>
    <div class="control">
        <textarea id="product-item-comment-<?= $block->escapeHtmlAttr($item->getWishlistItemId()) ?>"
                  placeholder="<?= /* @noEscape */ $this->helper(\Magento\Wishlist\Helper\Data::class)->defaultCommentString() ?>"
                  name="description[<?= $block->escapeHtmlAttr($item->getWishlistItemId()) ?>]"
                  title="<?= $block->escapeHtmlAttr(__('Comment')) ?>"
                  class="product-item-comment form-textarea mt-1 block w-full"
            <?= $item->getProduct()->isSaleable() ? '' : 'disabled="disabled"' ?>
        ><?= ($block->escapeHtml($item->getDescription())) ?></textarea>
    </div>
</div>
