<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info;
use Magento\Wishlist\Model\Item;

/** @var Info $block */

/** @var Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<strong class="product-item-name">
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>" class="product-item-link">
        <?= $block->escapeHtml($product->getName()) ?>
    </a>
</strong>
