<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Wishlist\Block\Customer\Wishlist\Button;

/** @var Button $block */
?>

<?php if ($block->getWishlist()->getItemsCount()) : ?>
    <button type="submit"
            name="do"
            title="<?= $block->escapeHtmlAttr(__('Update Wish List')) ?>"
            class="action update">
        <span><?= $block->escapeHtml(__('Update Wish List')) ?></span>
    </button>
<?php endif;?>
