<?php declare(strict_types=1);
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

?>
<a :href="'<?= $escaper->escapeUrl($block->getBaseUrl()) ?>' + item.url_key + (item.url_suffix || '')"
   class="relative flex items-center bg-white product photo product-item-photo"
   style="padding-top:100%"
   tabindex="-1">
        <span class="absolute top-0 left-0 flex flex-wrap content-center w-full h-full p-2
            overflow-hidden align-center hover:shadow-sm">
            <img class="self-center w-full h-auto"
                 :src="item.small_image.url"
                 :alt="item.small_image.label"
                 loading="lazy"
                 width="500"
                 height="500"
            />
        </span>
</a>

<p class="flex items-center justify-center px-1 pt-3 text-primary">
    <a class="truncate product-item-link"
       :href="'<?= $escaper->escapeUrl($block->getBaseUrl()) ?>' + item.url_key + (item.url_suffix || '')"
    >
        <span x-html="item.name"></span>
    </a>
</p>
<p class="pt-1 text-lg text-center text-gray-900"
   x-text="hyva.formatPrice(item.price_range.minimum_price.final_price.value)"></p>
<p class="flex flex-wrap gap-2 inline p-3">
    <a class="justify-center w-auto mr-auto btn btn-primary"
       :href="'<?= $escaper->escapeUrl($block->getBaseUrl()) ?>' + item.url_key + (item.url_suffix || '')"
    >
        <span class="inline"><?= $escaper->escapeHtml(__('View Product')) ?></span>
    </a>
    <span class="inline-flex gap-2">
        <?php if ($compareViewModel->showInProductList()): ?>
            <button @click.prevent="hyva.slider.addToCompare(item.id)"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                    class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex
                    items-center justify-center text-gray-500 hover:text-yellow-500"
            >
            <?= $heroicons->scaleHtml("w-5 h-5") ?>
            </button>
        <?php endif; ?>
        <?php if ($wishlistViewModel->isEnabled()): ?>
            <button
                aria-label="<?= $escaper->escapeHtml(__('Add to Wish List')) ?>"
                @click.prevent="hyva.slider.addToWishlist(item.id)"
                class="inline-flex items-center justify-center w-10 h-10 p-0 ml-auto
                                            text-gray-500 bg-gray-200 border-0 rounded-full hover:text-red-600"
            >
                <?= $heroicons->heartHtml("w-5 h-5", 25, 25) ?>
            </button>
        <?php endif; ?>
    </span>
</p>
