<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);
?>

<span class="widget block-product-link-inline">
    <a class="underline font-medium" <?= /* @noEscape */ $block->getLinkAttributes() ?>>
        <span><?= $block->escapeHtml($block->getLabel()) ?></span>
    </a>
</span>
