<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit;
use Magento\Framework\Escaper;

/** @var Edit $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);

$item = $block->getItem();
if ($item->getProductType() === 'configurable') {
    $productOptions = $item->getProduct()->getTypeInstance()->getOrderOptions($item->getProduct());
    $productName = $productOptions["simple_name"];
} else {
    $productName = $item->getName();
}
?>
<?php if ($block->isProductVisibleInSiteVisibility()): ?>
    <a
        class="btn p-2"
        href="<?= $escaper->escapeUrl($block->getConfigureUrl()) ?>"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Edit %1', $productName)) ?>"
    >
        <?= $lucideIcons->pencilHtml('', 20, 20, ['aria-hidden' => 'true']) ?>
    </a>
<?php endif ?>
